<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Harishankar" failures="0" tests="1" name="tesrCases.TC_11_DataDrivenTesting_ProductImagePageInImageToImageGeneration" time="83.370" errors="1" timestamp="2024-10-15T17:13:08 IST" skipped="0">
  <testcase classname="tesrCases.TC_11_DataDrivenTesting_ProductImagePageInImageToImageGeneration" name="DataDrivenTesting_ProductImagePageInImageToImageGeneration" time="83.370">
    <error message="An unexpected error occurred while clicking the &#039;Use an Asset&#039; Next button." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: An unexpected error occurred while clicking the 'Use an Asset' Next button.
at pageObjects.ImageCraftImageToImage.ClickOnuploadimgUseAnAssetNextButton(ImageCraftImageToImage.java:285)
at tesrCases.TC_11_DataDrivenTesting_ProductImagePageInImageToImageGeneration.DataDrivenTesting_ProductImagePageInImageToImageGeneration(TC_11_DataDrivenTesting_ProductImagePageInImageToImageGeneration.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on windows (ada5e259dce0eb3f2eaa01ba49512f42)] -> xpath: //h2[text()='Prompt']] (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\HP\AppData\Local\T...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50200}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50200/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: ada5e259dce0eb3f2eaa01ba49512f42
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at pageObjects.ImageCraftImageToImage.ClickOnuploadimgUseAnAssetNextButton(ImageCraftImageToImage.java:266)
... 27 more
]]>
    </error>
  </testcase> <!-- DataDrivenTesting_ProductImagePageInImageToImageGeneration -->
  <system-out/>
</testsuite> <!-- tesrCases.TC_11_DataDrivenTesting_ProductImagePageInImageToImageGeneration -->
